services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  blog:
    container_name: blog
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/media:/home/app/blog/src/media
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/media:/var/blog/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  celery:
    build:
      context: .
    container_name: celery
    restart: always
    depends_on:
      - redis
    command: celery -A src.config worker -l info
  flower:
    build:
      context: .
    container_name: flower
    restart: always
    depends_on:
      - celery
    ports:
      - "5555:5555"
    command: celery -A src.config flower -l info
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  postgres_backup:
