services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 5s
  blog:
    container_name: blog
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/media:/blog/src/media
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/media:/var/blog/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 5s
  celery:
    build:
      context: .
    container_name: celery
    restart: always
    depends_on:
      - redis
    command: celery -A config worker -l info
    healthcheck:
      test: [ "CMD", "executable" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  flower:
    build:
      context: .
    container_name: flower
    restart: always
    depends_on:
      - celery
    ports:
      - "5555:5555"
    command: celery -A config flower -l info
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping", "|| exit 1" ]
      interval: 1m
      timeout: 10s
      retries: 30
volumes:
  postgres_data:
  postgres_backup:
