"""add refresh token table

Revision ID: 06ce3363a9bf
Revises: 1fe5898b643c
Create Date: 2023-06-20 02:41:31.026930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ce3363a9bf'
down_revision = '1fe5898b643c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
