"""add refresh token table in db

Revision ID: 995ca71ee8d4
Revises: f79db04dca1b
Create Date: 2023-06-20 02:52:35.819482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995ca71ee8d4'
down_revision = 'f79db04dca1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
