"""change user model to mine

Revision ID: 1fe5898b643c
Revises: e2ca04ca3c68
Create Date: 2023-06-19 17:11:16.815709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe5898b643c'
down_revision = 'e2ca04ca3c68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('password', sa.String(length=1024), nullable=False))
    op.drop_column('account', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('account', 'password')
    # ### end Alembic commands ###
