"""change to mapping

Revision ID: e2ca04ca3c68
Revises: 9c105589544b
Create Date: 2023-06-18 18:13:13.611205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2ca04ca3c68'
down_revision = '9c105589544b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('posttag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posttag', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posttag', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posttag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
