"""add refresh token tablename

Revision ID: f79db04dca1b
Revises: 06ce3363a9bf
Create Date: 2023-06-20 02:42:27.647715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79db04dca1b'
down_revision = '06ce3363a9bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
